retrieve_ENO_DEV1/objects/Card__c.object
<CustomObject>
    <description>Used to generate a &quot;Card View&quot; calendar in Booekr25 in which a generic overview of the ongoing planning is shown.</description>
    <fields>
        <fullName>API_Name__c</fullName>
        <externalId>true</externalId>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Performer__c.object
<CustomObject>
    <description>Shows the Performer Profile</description>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Reservation_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Card</label>
        <referenceTo>Card__c</referenceTo>
        <relationshipLabel>Reservation Cards</relationshipLabel>
        <relationshipName>Reservation_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservation</label>
        <referenceTo>B25__Reservation__c</referenceTo>
        <relationshipLabel>Reservation Cards</relationshipLabel>
        <relationshipName>Reservation_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reservation Card</label>
    <nameField>
        <displayFormat>RC-{00000000}</displayFormat>
        <label>Reservation Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Reservation_Performer__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Reservation Performers</relationshipLabel>
        <relationshipName>Reservation_Performers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservation</label>
        <referenceTo>B25__Reservation__c</referenceTo>
        <relationshipLabel>Reservation Performers</relationshipLabel>
        <relationshipName>Reservation_Performers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reservation Performer</label>
    <nameField>
        <displayFormat>RP-{0000000}</displayFormat>
        <label>Reservation Performer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Reservation_Staff__c.object
<CustomObject>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>B25__Reservation__c</referenceTo>
        <relationshipLabel>Reservation Staffs</relationshipLabel>
        <relationshipName>Reservation_Staffs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>B25__Staff__c</referenceTo>
        <relationshipLabel>Reservation Staffs</relationshipLabel>
        <relationshipName>Reservation_Staffs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Reservation Staff</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reservation Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Shift_Staff__c.object
<CustomObject>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>B25__Reservation__c</referenceTo>
        <relationshipLabel>Shift Staffs</relationshipLabel>
        <relationshipName>Shift_Staffs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>B25__Staff__c</referenceTo>
        <relationshipLabel>Shift Staffs</relationshipLabel>
        <relationshipName>Shift_Staffs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shift Staff</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Shift Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shift Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Test_B25_Reservation.cls
@IsTest
private class Test_B25_Reservation {
    @isTest private static void testOvertime() {
        B25__Reservation_Status__c status = new B25__Reservation_Status__c();
        status.Name = 'Overtime';
        Database.insert(status);

        B25__Reservation__c reservation = new B25__Reservation__c();
        reservation.Overtime__c = true;
        reservation.B25__Start__c = DateTime.now();
        reservation.B25__End__c = DateTime.now().addHours(1);
        Database.insert(reservation);

        System.assertEquals(status.Id, [SELECT B25__Status__c FROM B25__Reservation__c LIMIT 1].B25__Status__c);
    }

    @isTest private static void testDimensionJunctions() {
    
        B25__Reservation__c reservation = new B25__Reservation__c();
        reservation.B25__Start__c = DateTime.now();
        reservation.B25__End__c = DateTime.now().addHours(1);
        Database.insert(reservation);

        Card__c card = new Card__c();
        card.Name ='a';
        card.API_Name__c = 'a';
        Database.insert(card);

        Reservation_Card__c resCard = new Reservation_Card__c();
        resCard.Reservation__c = reservation.Id;
        resCard.Card__c = card.Id;
        Database.insert(resCard);

        Performer__c performer = new Performer__c();
        performer.Name ='a';
        Database.insert(performer);

        Reservation_Performer__c resPerformer = new Reservation_Performer__c();
        resPerformer.Reservation__c = reservation.Id;
        resPerformer.Performer__c = performer.Id;
        Database.insert(resPerformer);

        B25__Staff__c staff = new B25__Staff__c();
        staff.Name = 'a';
        Database.insert(staff);

        Reservation_Staff__c resStaff = new Reservation_Staff__c();
        resStaff.Reservation__c = reservation.Id;
        resStaff.Staff__c = staff.Id;
        Database.insert(resStaff);

        Shift_Staff__c shiftStaff = new Shift_Staff__c();
        shiftStaff.Reservation__c = reservation.Id;
        shiftStaff.Staff__c = staff.Id;
        Database.insert(shiftStaff);

        System.assertEquals(1, [SELECT Id FROM B25__Reservation__c].size());
    }

    @isTest private static void testCtrl_StaffResourceTitle() {
        // B25.Util_PluginManager.DynamicResourceTitleData a = (B25.Util_PluginManager.DynamicResourceTitleData)JSON.deserialize('{}', B25.Util_PluginManager.DynamicResourceTitleData.class);
        // Ctrl_StaffResourceTitle b = new Ctrl_StaffResourceTitle();
        // b.calculateResourceTitles(a);
    }
}