retrieve_ENO_DEV1/objects/Cast_Member__c.object
<CustomObject>
    <description>Related to both a Run (of a production) and a performer, this object determines who plays what role in the run.</description>
    <fields>
        <fullName>Cast_Cover__c</fullName>
        <label>Cast/Cover</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cast A</fullName>
                </value>
                <value>
                    <fullName>Cast B</fullName>
                </value>
                <value>
                    <fullName>Cast C</fullName>
                </value>
                <value>
                    <fullName>Cast D</fullName>
                </value>
                <value>
                    <fullName>Cover</fullName>
                </value>
                <value>
                    <fullName>Creative Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <description>Name of the Production</description>
        <formula>Run__r.Production__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Production</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Run__c</fullName>
        <label>Run</label>
        <referenceTo>Run__c</referenceTo>
        <relationshipLabel>Cast Members</relationshipLabel>
        <relationshipName>Cast_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cast Member</label>
    <nameField>
        <label>Cast Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cast Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Performer__c.object
<CustomObject>
    <description>Shows the Performer Profile</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soprano</fullName>
                </value>
                <value>
                    <fullName>Mezzo-soprano</fullName>
                </value>
                <value>
                    <fullName>Contralto</fullName>
                </value>
                <value>
                    <fullName>Countertenor</fullName>
                </value>
                <value>
                    <fullName>Tenor</fullName>
                </value>
                <value>
                    <fullName>Baritone</fullName>
                </value>
                <value>
                    <fullName>Bass-Baritone</fullName>
                </value>
                <value>
                    <fullName>Bass</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Conductor</fullName>
                </value>
                <value>
                    <fullName>Designer (Any)</fullName>
                </value>
                <value>
                    <fullName>Choreographer/ Movement Director</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Actor</fullName>
                </value>
                <value>
                    <fullName>Dancer</fullName>
                </value>
                <value>
                    <fullName>Acrobat</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Chorus (soprano)</fullName>
                </value>
                <value>
                    <fullName>Chorus (mezzo)</fullName>
                </value>
                <value>
                    <fullName>Chorus (Tenor)</fullName>
                </value>
                <value>
                    <fullName>Chorus (Bass)</fullName>
                </value>
                <value>
                    <fullName>Chorus (Countertenor)</fullName>
                </value>
                <value>
                    <fullName>Extra Chorus</fullName>
                </value>
                <value>
                    <fullName>ENO staff appearing onstage</fullName>
                </value>
                <value>
                    <fullName>Assistant Conductor</fullName>
                    <isActive>false</isActive>
                    <label>Assistant Conductor</label>
                </value>
                <value>
                    <fullName>If Role is &apos;Other&apos; please specify</fullName>
                    <isActive>false</isActive>
                    <label>If Role is &apos;Other&apos; please specify</label>
                </value>
                <value>
                    <fullName>Revival Director (if applicable)</fullName>
                    <isActive>false</isActive>
                    <label>Revival Director (if applicable)</label>
                </value>
                <value>
                    <fullName>Staff Director (if applicable)</fullName>
                    <isActive>false</isActive>
                    <label>Staff Director (if applicable)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Person_Group__c.object
<CustomObject>
    <fields>
        <fullName>Store_in_Selected_Person_Groups__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, the name of this person group will be populated on select in the Selected Person Groups Box.</inlineHelpText>
        <label>Store in Selected Person Groups</label>
        <type>Checkbox</type>
    </fields>
    <label>Person Group</label>
    <nameField>
        <label>Person Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Person_Group_Performer__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Person Group Performers</relationshipLabel>
        <relationshipName>Person_Group_Performers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Group__c</fullName>
        <label>Person Group</label>
        <referenceTo>Person_Group__c</referenceTo>
        <relationshipLabel>Person Group Performers</relationshipLabel>
        <relationshipName>Person_Group_Performers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person Group Performer</label>
    <nameField>
        <displayFormat>PGP-{0000000000}</displayFormat>
        <label>Person Group Performer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Group Performers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Production__c.object
<CustomObject>
    <description>Shows the Production Profiles</description>
    <fields>
        <fullName>Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Productions</relationshipLabel>
        <relationshipName>Productions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Reservation_Performer__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Reservation Performers</relationshipLabel>
        <relationshipName>Reservation_Performers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reservation Performer</label>
    <nameField>
        <displayFormat>RP-{0000000}</displayFormat>
        <label>Reservation Performer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Reservation_Staff__c.object
<CustomObject>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>B25__Staff__c</referenceTo>
        <relationshipLabel>Reservation Staffs</relationshipLabel>
        <relationshipName>Reservation_Staffs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Reservation Staff</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reservation Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservation Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Run__c.object
<CustomObject>
    <description>Holds data of a Production/Show in a season.</description>
    <fields>
        <fullName>Production__c</fullName>
        <label>Production</label>
        <referenceTo>Production__c</referenceTo>
        <relationshipLabel>Runs</relationshipLabel>
        <relationshipName>Runs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Run</label>
    <nameField>
        <label>Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Shift_Staff__c.object
<CustomObject>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>B25__Staff__c</referenceTo>
        <relationshipLabel>Shift Staffs</relationshipLabel>
        <relationshipName>Shift_Staffs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shift Staff</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Shift Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shift Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Work_Period__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Departments</valueSetName>
        </valueSet>
    </fields>
    <label>Work Period</label>
    <nameField>
        <label>Work Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Periods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Test_ENOFormLogic.cls
@IsTest
public class Test_ENOFormLogic {

    @TestSetup
    static void makeData(){
        B25__System_Setting__c systemSetting = new B25__System_Setting__c();
        systemSetting.Name ='Reservation Form Customizer Class';
        systemSetting.B25__String_Value__c = 'ENOFormLogic';
        Database.insert(systemSetting);
    }

    @IsTest
    private static void testSearch() {
        B25__Service_Type__c servicetype = new B25__Service_Type__c();
        servicetype.Name = 'F&B';
        Database.insert(servicetype);

        B25__Service__c service = new B25__Service__c();
        service.Name = 'a';
        service.B25__Service_Type__c = servicetype.Id;
        Database.insert(service);

        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );

        B25.Test_FormHelper.TestRelatedListEvent changeEvent4 = new B25.Test_FormHelper.TestRelatedListEvent();
        changeEvent4.relatedSObjectType = B25__Service_Reservation__c.SObjectType;
        changeEvent4.addedSObjectId = service.Id;
        changeEvent4.changedRelatedListItem = new B25__Service_Reservation__c(
            B25__Service__c = service.Id
        );
        B25.Test_FormHelper.runRelatedListAddEvent(formContext, changeEvent4);
    }
    
    @isTest private static void testSearchPerformer() {
        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );

        B25.Test_FormHelper.TestSearchContext changeEvent = new B25.Test_FormHelper.TestSearchContext();
        changeEvent.toSearchSObjectType = Performer__c.SObjectType;
        changeEvent.toCreateSObjectType = Reservation_Performer__c.SObjectType;
        changeEvent.searchTerm = 'as';
        changeEvent.fieldName = 'Name';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent);
    }

    @isTest private static void testSearchPerformer2() {
        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );

        B25.Test_FormHelper.TestSearchContext changeEvent = new B25.Test_FormHelper.TestSearchContext();
        changeEvent.toSearchSObjectType = Performer__c.SObjectType;
        changeEvent.toCreateSObjectType = Reservation_Performer__c.SObjectType;
        changeEvent.searchTerm = '-';
        changeEvent.fieldName = 'Name';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent);
    }

    @isTest private static void testSearchPerformer3() {

        Production__c production = new Production__c();
        production.Name = 'a';
        Database.insert(production);

        Run__c run = new Run__c();
        run.Name = 'b';
        run.Production__c = production.Id;
        Database.insert(run);

        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1),
            Run__c = run.Id
        );

        B25.Test_FormHelper.TestSearchContext changeEvent = new B25.Test_FormHelper.TestSearchContext();
        changeEvent.toSearchSObjectType = Performer__c.SObjectType;
        changeEvent.toCreateSObjectType = Reservation_Performer__c.SObjectType;
        changeEvent.searchTerm = '-';
        changeEvent.fieldName = 'Name';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent);
    }

    @isTest private static void testSearchPerformerDash() {
        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );
        B25.Test_FormHelper.TestSearchContext changeEvent2 = new B25.Test_FormHelper.TestSearchContext();
        changeEvent2.toSearchSObjectType = Performer__c.SObjectType;
        changeEvent2.toCreateSObjectType = Reservation_Performer__c.SObjectType;
        changeEvent2.fieldName = 'Name';
        changeEvent2.searchTerm = '-';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent2);
    }
    @isTest private static void testSearchPerformerGTE() {

        Person_Group__c pg = new Person_Group__c();
        pg.Name = 'Name';
        pg.Store_in_Selected_Person_Groups__c = true;
        Database.insert(pg);

        Performer__c perf = new Performer__c();
        perf.Name = 'perf';
        perf.Active__c = true;
        Database.insert(perf);  

        Person_Group_Performer__c pgPerf = new Person_Group_Performer__c();
        pgPerf.Performer__c = perf.Id;
        pgPerf.Person_Group__c = pg.Id;
        Database.insert(pgPerf);

        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1),
            Selected_Person_Groups__c = 'aa, a'
        );
        B25.Test_FormHelper.TestSearchContext changeEvent3 = new B25.Test_FormHelper.TestSearchContext();
        changeEvent3.toSearchSObjectType = Performer__c.SObjectType;
        changeEvent3.toCreateSObjectType = Reservation_Performer__c.SObjectType;
        changeEvent3.fieldName = 'Name';
        changeEvent3.searchTerm = '>';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent3);


        B25.Test_FormHelper.TestRelatedListEvent changeEvent5 = new B25.Test_FormHelper.TestRelatedListEvent();
        changeEvent5.relatedSObjectType = Reservation_Performer__c.SObjectType;
        changeEvent5.addedSObjectId = pg.Id;
        changeEvent5.changedRelatedListItem = new Reservation_Performer__c(
            Performer__c = perf.Id
        );
        B25.Test_FormHelper.runRelatedListAddEvent(formContext, changeEvent5);
    }

    @isTest private static void testChorusStaff(){
        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );
        Performer__c performer = new Performer__c();
        performer.Name = 'Performer';
        performer.Role__c = 'Chorus (soprano)';
        Database.insert(performer);

        B25.Test_FormHelper.TestRelatedListEvent changeEvent5 = new B25.Test_FormHelper.TestRelatedListEvent();
        changeEvent5.relatedSObjectType = Reservation_Performer__c.SObjectType;
        changeEvent5.addedSObjectId = 'all-chorus';
        changeEvent5.changedRelatedListItem = new Reservation_Performer__c(
            Performer__c = performer.Id
        );
        B25.Test_FormHelper.runRelatedListAddEvent(formContext, changeEvent5);
    }

    @isTest private static void testCastStaff(){

        Production__c production = new Production__c();
        production.Name = 'a';
        Database.insert(production);

        Run__c run = new Run__c();
        run.Name = 'b';
        run.Production__c = production.Id;
        Database.insert(run);

        Performer__c performer = new Performer__c();
        performer.Name = 'a';
        performer.Active__c = true;
        Database.insert(performer);

        Cast_Member__c castMember = new Cast_Member__c();
        castMember.Performer__c = performer.Id;
        castMember.Cast_Cover__c = 'Cast A';
        castMember.Run__c = run.Id;
        Database.insert(castMember);

        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1),
            Run__c = run.Id
        );
        B25__Staff__c staff = new B25__Staff__c();
        staff.Name = 'staff';
        Database.insert(staff);

        B25.Test_FormHelper.TestRelatedListEvent changeEvent5 = new B25.Test_FormHelper.TestRelatedListEvent();
        changeEvent5.relatedSObjectType = Reservation_Staff__c.SObjectType;
        changeEvent5.addedSObjectId = 'all-castA';
        changeEvent5.changedRelatedListItem = new Reservation_Staff__c(
            Staff__c = staff.Id
        );
        B25.Test_FormHelper.runRelatedListAddEvent(formContext, changeEvent5);
    }


    @isTest private static void testSearchStaff(){
        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );
        B25__Staff__c staff = new B25__Staff__c();
        staff.Name = 'staff';
        Database.insert(staff);

        B25.Test_FormHelper.TestSearchContext changeEvent3 = new B25.Test_FormHelper.TestSearchContext();
        changeEvent3.toSearchSObjectType = B25__Staff__c.SObjectType;
        changeEvent3.toCreateSObjectType = Reservation_Staff__c.SObjectType;
        changeEvent3.fieldName = 'Name';
        changeEvent3.searchTerm = '>';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent3);

        B25.Test_FormHelper.TestRelatedListEvent changeEvent5 = new B25.Test_FormHelper.TestRelatedListEvent();
        changeEvent5.relatedSObjectType = Reservation_Staff__c.SObjectType;
        changeEvent5.addedSObjectId = staff.Id;
        changeEvent5.changedRelatedListItem = new Reservation_Staff__c(
            Staff__c = staff.Id
        );
        B25.Test_FormHelper.runRelatedListAddEvent(formContext, changeEvent5);
    }

    @isTest private static void testSearchStaff2(){
        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );
        B25__Staff__c staff = new B25__Staff__c();
        staff.Name = 'staff';
        Database.insert(staff);

        B25.Test_FormHelper.TestSearchContext changeEvent3 = new B25.Test_FormHelper.TestSearchContext();
        changeEvent3.toSearchSObjectType = B25__Staff__c.SObjectType;
        changeEvent3.toCreateSObjectType = Reservation_Staff__c.SObjectType;
        changeEvent3.fieldName = 'Name';
        changeEvent3.searchTerm = 'asd';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent3);

        B25.Test_FormHelper.TestRelatedListEvent changeEvent5 = new B25.Test_FormHelper.TestRelatedListEvent();
        changeEvent5.relatedSObjectType = Reservation_Staff__c.SObjectType;
        changeEvent5.addedSObjectId = staff.Id;
        changeEvent5.changedRelatedListItem = new Reservation_Staff__c(
            Staff__c = staff.Id
        );
        B25.Test_FormHelper.runRelatedListAddEvent(formContext, changeEvent5);
    }
    @isTest private static void testSearchStaff3(){
        Work_Period__c workPeriod = new Work_Period__c();
        workPeriod.Department__c = 'Costume';
        Database.insert(workPeriod);

        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1),
            Work_Period__c = workPeriod.Id
        );
        B25__Staff__c staff = new B25__Staff__c();
        staff.Name = 'staff';
        staff.Department__c = 'Costume';
        Database.insert(staff);

        B25.Test_FormHelper.TestSearchContext changeEvent3 = new B25.Test_FormHelper.TestSearchContext();
        changeEvent3.toSearchSObjectType = B25__Staff__c.SObjectType;
        changeEvent3.toCreateSObjectType = Shift_Staff__c.SObjectType;
        changeEvent3.fieldName = 'Name';
        changeEvent3.searchTerm = 'staff';
        B25.Test_FormHelper.runLookupOverrideSearch(formContext, changeEvent3);

        B25.Test_FormHelper.TestRelatedListEvent changeEvent5 = new B25.Test_FormHelper.TestRelatedListEvent();
        changeEvent5.relatedSObjectType = Shift_Staff__c.SObjectType;
        changeEvent5.addedSObjectId = staff.Id;
        changeEvent5.changedRelatedListItem = new Shift_Staff__c(
            Staff__c = staff.Id
        );
        B25.Test_FormHelper.runRelatedListAddEvent(formContext, changeEvent5);
    }

    @isTest private static void testResource(){
        B25__Resource_type__c resourceType = new B25__Resource_type__c();
        resourceType.Name = 'test';
        Database.insert(resourceType);

        B25__Resource__c resource = new B25__Resource__c();
        resource.NAme = 'Stage';
        resource.B25__Resource_type__c = resourceType.Id;
        Database.insert(resource);
        
        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1),
            B25__Resource__c = resource.Id
        );

        B25.Test_FormHelper.TestChangeEvent changeEvent = new B25.Test_FormHelper.TestChangeEvent();
        changeEvent.sObjectField = B25__Reservation__c.B25__Resource__c;
        changeEvent.newValue = resource.Id;
        changeEvent.previousValue = null;
        B25.Test_FormHelper.runFieldChangeEvent(formContext, changeEvent);
    }

    @isTest private static void testServiceReservationChange(){
        B25__Service_Type__c servicetype = new B25__Service_Type__c();
        servicetype.Name = 'F&B';
        Database.insert(servicetype);

        B25__Service__c service = new B25__Service__c();
        service.Name = 'a';
        service.B25__Service_Type__c = servicetype.Id;
        Database.insert(service);

        B25.Test_FormHelper.TestFormContext formContext = new B25.Test_FormHelper.TestFormContext();
        formContext.reservation = new B25__Reservation__c(
            B25__StartLocal__c = Datetime.now(),
            B25__EndLocal__c = Datetime.now().addHours(1)
        );

        B25.Test_FormHelper.TestChangeEvent changeEvent = new B25.Test_FormHelper.TestChangeEvent();
        changeEvent.sObjectField = B25__Service_Reservation__c.Original_Quantity__c;
        changeEvent.newValue = 2;
        changeEvent.previousValue = 1;
        B25.Test_FormHelper.runFieldChangeEvent(formContext, changeEvent);
    }
    @isTest private static void fakeTitleTest() {
        Ctrl_StaffResourceTitle.fakeUnitTest();
    }
}