retrieve_ENO_DEV1/objects/Financial_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Annual_Non_VAT__c</fullName>
        <label>Annual Non VAT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gift_Aid_Percent__c</fullName>
        <label>Gift Aid Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT_Value__c</fullName>
        <label>VAT Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financial Settings</label>
</CustomObject>

retrieve_ENO_DEV1/objects/Membership_Level_Benefit__mdt.object
<CustomObject>
    <fields>
        <fullName>Benefit_Value__c</fullName>
        <label>Benefit Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Membership_Name__c</fullName>
        <label>Membership Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Membership Level Benefit</label>
    <pluralLabel>Membership Level Benefits</pluralLabel>
</CustomObject>

retrieve_ENO_DEV1/objects/Split__c.object
<CustomObject>
    <fields>
        <fullName>Account_No__c</fullName>
        <label>NL Account Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRM_ID__c</fullName>
        <label>CRM ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name (or Organisation Name)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gen_Posting_Type__c</fullName>
        <label>VAT4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gen_Prod_Posting_Group__c</fullName>
        <label>VAT3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>npe01__OppPayment__c</referenceTo>
        <relationshipName>Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shortcut_Dimension_1_Code__c</fullName>
        <label>Department Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shortcut_Dimension_2_Code__c</fullName>
        <label>Project Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Surname__c</fullName>
        <label>Surname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAT_Bus_Posting_Group__c</fullName>
        <label>VAT2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAT_Prod_Posting_Group73912_XP__c</fullName>
        <label>VAT1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Split</label>
    <nameField>
        <displayFormat>SPLIT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments Split</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/ConstantsUtilsPaymentsSplit.cls
/**
 * Created by amacari on 7/5/2021.
 */

public with sharing class ConstantsUtilsPaymentsSplit {

    public static Split__c createPaymentSplit(Id paymentId, Decimal crmId, String lastName, String firstName, String generalLedgerCode, String departmentCode, String projectCode, String VAT1, String VAT2, String VAT3, String VAT4){
        Split__c split = new Split__c();
        split.Payment__c = paymentId;
        split.CRM_ID__c = crmId;
        split.Surname__c = lastName;
        split.First_Name__c = firstName;
        split.Account_No__c = generalLedgerCode;
        split.Shortcut_Dimension_1_Code__c = departmentCode;
        split.Shortcut_Dimension_2_Code__c = projectCode;
        split.VAT_Prod_Posting_Group73912_XP__c = VAT1;
        split.VAT_Bus_Posting_Group__c = VAT2;
        split.Gen_Prod_Posting_Group__c = VAT3;
        split.Gen_Posting_Type__c = VAT4;
        return split;
    }

    public static Map<String, Decimal> createMembershipSplitMap(){
        Map<String, Decimal> membershipSplitMap = new Map<String, Decimal>();
        Map<String, Membership_Level_Benefit__mdt> mlbMap = Membership_Level_Benefit__mdt.getAll();
        for(String membershipLevelBenefit : mlbMap.keySet()){
            membershipSplitMap.put(mlbMap.get(membershipLevelBenefit).Membership_Name__c, mlbMap.get(membershipLevelBenefit).Benefit_Value__c);
        }
        return membershipSplitMap;
    }

    public static final List<String> RECORD_TYPE_ID_LIST = new List<String> {
            Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Donation').getRecordTypeId(),
            Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('In-Kind Gift').getRecordTypeId(),
            Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Grant').getRecordTypeId(),
            Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Philanthropy').getRecordTypeId(),
            Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Memberships').getRecordTypeId()
    };

    public static final Financial_Settings__c FINANCIAL_SETTINGS = [
            SELECT Annual_Non_VAT__c, Gift_Aid_Percent__c, VAT_Value__c
            FROM Financial_Settings__c
    ];

}