retrieve_ENO_DEV1/objects/Ghost_Planning__c.object
<CustomObject>
    <label>Ghost Planning</label>
    <nameField>
        <label>Ghost Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ghost Plannings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Ghost_Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Ghost_Planning__c</fullName>
        <label>Ghost Planning</label>
        <referenceTo>Ghost_Planning__c</referenceTo>
        <relationshipLabel>Ghost Planning Version</relationshipLabel>
        <relationshipName>Ghost_Planning_Version</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ghost Planning Version</label>
    <nameField>
        <label>Ghost Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ghost Planning Version</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Test_Ctrl_CardReport.cls
@isTest
private class Test_Ctrl_CardReport {
    @isTest 
    private static void testCardReport() {
        PageReference pageRef = Page.cardReport;
        Test.setCurrentPage(pageRef);
        
        B25__Reservation__c rsv = Test_DataHelper.createBooker();

        Ctrl_CardReport controller = new Ctrl_CardReport();
        System.assertEquals(Date.today(), controller.tableRows[0].rowDate);
    }

    @isTest 
    private static void testSearchGhostPlanning() {
        Ghost_Planning__c ghostPlanning = new Ghost_Planning__c();
        Database.insert(ghostPlanning);
        
        Ghost_Planning_Version__c ghostPlanningVersion = new Ghost_Planning_Version__c();
        ghostPlanningVersion.Name = 'name';
        ghostPlanningVersion.Ghost_planning__c = ghostPlanning.Id;
        Database.insert(ghostPlanningVersion);

        System.assertEquals(1, Ctrl_CardReport.searchGhostPlanningVersion('name', null).size());
    }
}