retrieve_ENO_DEV1/objects/Outbound_Manager_Request_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Business_Error_Codes__c</fullName>
        <label>Business Error Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Retry_Count__c</fullName>
        <label>Max Retry Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Class_Name__c</fullName>
        <label>Request Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type_Name__c</fullName>
        <label>Request Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Succeeded_Response_Codes__c</fullName>
        <label>Succeeded Response Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Outbound Manager Request Type</label>
    <pluralLabel>Outbound Manager Request Types</pluralLabel>
</CustomObject>

retrieve_ENO_DEV1/objects/Outbound_Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Failed_By_Business_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed By Business Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Endpoint__c</fullName>
        <label>Request Endpoint</label>
        <length>16384</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transfered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfered</label>
        <type>Checkbox</type>
    </fields>
    <label>Outbound Transfer</label>
    <nameField>
        <label>Outbound Transfer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/SendJobOutbound.cls
/**
 * Created by ibuzau on 4/29/2021.
 */

global class SendJobOutbound implements Schedulable {


	private Map<String, Integer> retryLimitPerRequestType;
	private List<outbound_manager_request_type__mdt> outboundMDT;

    global void execute(SchedulableContext ctx) {
        List<Outbound_Transfer__c> jobs = [
                SELECT Id, Request_Body__c, Request_Endpoint__c
                FROM Outbound_Transfer__c
                WHERE Transfered__c = FALSE AND Failed_By_Business_Error__c = FALSE
        ];

		outboundMDT = [SELECT Id, request_class_name__c, request_type_name__c, max_retry_count__c, business_error_codes__c, succeeded_response_codes__c FROM outbound_manager_request_type__mdt];
		retryLimitPerRequestType = getRetryLimits(outboundMDT);

        WrapperInterface wrapperInterface = new WSDLExample();
        WSDLExample.wsdlResponse resp = new WSDLExample.wsdlResponse();

        for (Outbound_Transfer__c job : jobs) {
            if (job.Request_Body__c != null) {
                JSONParser body = JSON.createParser(job.Request_Body__c);
                while (body.nextToken() != null) {
                    if ((body.getCurrentToken() == JSONToken.FIELD_NAME) && (body.getText() == 'type')) {
                        body.nextToken();
                        System.debug(body.getText()); // returneaza account
                    }
                    if ((body.getCurrentToken() == JSONToken.FIELD_NAME) && (body.getText() == 'Id')) {
                        body.nextToken();
                        System.debug(body.getText());
                    }
                    if ((body.getCurrentToken() == JSONToken.FIELD_NAME) && (body.getText() == 'Name')) {
                        body.nextToken();
                        System.debug(body.getText());
                    }

                    resp = wrapperInterface.send();
                    if ((resp.code.startsWith('3') || resp.code.startsWith('4') || resp.code.startsWith('5')) && resp.errorMessage != null){
                        job.Failed_By_Business_Error__c = true;
                        job.Error_Code__c = Decimal.valueOf(resp.code);
                        job.Error_Message__c = resp.errorMessage;
                    } else {
                        job.Transfered__c = true;
                    }
                }
            }
        }
        update jobs;
        
    }

	public Map<String, Integer> getRetryLimits(List<outbound_manager_request_type__mdt> outboundMDT)
    {
        Map<String, Integer> toReturn = new Map<String, Integer>();

        for(outbound_manager_request_type__mdt mdt : outboundMDT)
        {
            toReturn.put(mdt.request_type_name__c, Integer.valueOf(mdt.max_retry_count__c));
        }

        return toReturn;
    }

}