retrieve_ENO_DEV1/objects/Outbound_Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Inserted_Time_In_Ms__c</fullName>
        <label>Inserted Time In Ms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Outbound Transfer</label>
    <nameField>
        <label>Outbound Transfer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/TransferDataWrapper.cls
public class TransferDataWrapper implements Comparable
{
    //The transferdata object
    public Outbound_Transfer__c transferData;

    /**
     * Constructor
     *
     * @param transferData
     */
    public TransferDataWrapper(Outbound_Transfer__c transferData)
    {
        this.transferData = transferData;
    }

    /**
     * Implement the compareTo function
     *
     * @param compareTo
     *
     * @return
     */
    public Integer compareTo(Object compareTo)
    {
        TransferDataWrapper compareToILData = (TransferDataWrapper) compareTo;

        if(transferData.inserted_time_in_ms__c < compareToILData.transferData.inserted_time_in_ms__c)
        {
            return -1;
        }

        return 1;
    }
}