retrieve_ENO_DEV1/objects/Outbound_manager_settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Lifetime_for_logged_data__c</fullName>
        <label>Lifetime for logged data</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Outbound Manager Settings</label>
</CustomObject>

retrieve_ENO_DEV1/objects/Outbound_Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Failed_By_Business_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed By Business Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Endpoint__c</fullName>
        <label>Request Endpoint</label>
        <length>16384</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transfered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfered</label>
        <type>Checkbox</type>
    </fields>
    <label>Outbound Transfer</label>
    <nameField>
        <label>Outbound Transfer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Test_DeleteOlderJobs.cls
/**
 * Created by ibuzau on 5/17/2021.
 */

@IsTest
private class Test_DeleteOlderJobs {

    @IsTest
    public static void testSendJobOutbound() {
        Outbound_manager_settings__c setting = new Outbound_manager_settings__c();
        setting.Lifetime_for_logged_data__c = 30;
        insert setting;

        Outbound_Transfer__c outboundTransfer = new Outbound_Transfer__c(
                Request_Body__c = '{"attributes":{"type":"Account","url":"/services/data/v51.0/sobjects/Account/0012500001RQjjUAAT"},"Id":"0012500001RQjjUAAT","Name":"Test9"}',
                Request_Endpoint__c = null,
                Transfered__c = true,
                Failed_By_Business_Error__c = false
        );

        insert outboundTransfer;

        Test.setCreatedDate(outboundTransfer.Id, Date.today().addMonths(-1));

        Test.startTest();
        DeleteOlderJobs deleteOlderJobs = new DeleteOlderJobs();
        deleteOlderJobs.execute(null);
        Test.stopTest();
        
        List<Outbound_Transfer__c> jobs =  [
                    SELECT Id
                    FROM Outbound_Transfer__c
                    WHERE Id = :outboundTransfer.Id
            ];
        Outbound_Transfer__c jobExpected= new Outbound_Transfer__c();

        System.assertEquals(0 , jobs.size());


    }
}