retrieve_ENO_DEV1/objects/Outbound_manager_settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Lifetime_for_logged_data__c</fullName>
        <label>Lifetime for logged data</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Outbound Manager Settings</label>
</CustomObject>

retrieve_ENO_DEV1/objects/Outbound_Transfer__c.object
<CustomObject>
    <fields>
        <fullName>Failed_By_Business_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed By Business Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transfered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfered</label>
        <type>Checkbox</type>
    </fields>
    <label>Outbound Transfer</label>
    <nameField>
        <label>Outbound Transfer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbound Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/DeleteOlderJobs.cls
/**
 * Created by ibuzau on 5/11/2021.
 */

global class DeleteOlderJobs implements Schedulable {
    global void execute(SchedulableContext ctx) {
        Outbound_manager_settings__c days = [SELECT Lifetime_for_logged_data__c FROM Outbound_manager_settings__c];
        Date noDays= (System.today() -(Integer) days.Lifetime_for_logged_data__c);

        List<Outbound_Transfer__c> olderJobs = [
                select Id
                FROM Outbound_Transfer__c
                WHERE CreatedDate <= :noDays
                And (Failed_By_Business_Error__c = True OR Transfered__c = True)

        ]; 
        if (!olderJobs.isEmpty())
            delete olderJobs;
    }
}