retrieve_ENO_DEV1/objects/Performer__c.object
<CustomObject>
    <description>Shows the Performer Profile</description>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Performer_Wig__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Performer Wigs</relationshipLabel>
        <relationshipName>Performer_Wigs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wig__c</fullName>
        <label>Wig</label>
        <referenceTo>Wig__c</referenceTo>
        <relationshipLabel>Performers</relationshipLabel>
        <relationshipName>Performer_Wigs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performer Wig</label>
    <nameField>
        <displayFormat>PW-{00000000}</displayFormat>
        <label>Performer Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performer Wigs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Production__c.object
<CustomObject>
    <description>Shows the Production Profiles</description>
    <fields>
        <fullName>Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Productions</relationshipLabel>
        <relationshipName>Productions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production</label>
    <nameField>
        <label>Production Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Run__c.object
<CustomObject>
    <description>Holds data of a Production/Show in a season.</description>
    <fields>
        <fullName>Production__c</fullName>
        <label>Production</label>
        <referenceTo>Production__c</referenceTo>
        <relationshipLabel>Runs</relationshipLabel>
        <relationshipName>Runs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Run</label>
    <nameField>
        <label>Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Run_Wig__c.object
<CustomObject>
    <fields>
        <fullName>Run__c</fullName>
        <label>Run</label>
        <referenceTo>Run__c</referenceTo>
        <relationshipLabel>Wigs</relationshipLabel>
        <relationshipName>Run_Wigs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wig__c</fullName>
        <label>Wig</label>
        <referenceTo>Wig__c</referenceTo>
        <relationshipLabel>Runs</relationshipLabel>
        <relationshipName>Run_Wigs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Run Wig</label>
    <nameField>
        <displayFormat>RW-{00000000}</displayFormat>
        <label>Run Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Run Wigs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Wig__c.object
<CustomObject>
    <fields>
        <fullName>Active_Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Wigs (Active Performer)</relationshipLabel>
        <relationshipName>Wigs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Wigs</relationshipLabel>
        <relationshipName>Wigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wig_Label_Ref_Number__c</fullName>
        <inlineHelpText>Wig Label Number</inlineHelpText>
        <label>Wig Label Ref Number</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Wig</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Wig_Performer_Run__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Wig Performers &amp; Runs</relationshipLabel>
        <relationshipName>Wig_Performers_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Run</label>
        <referenceTo>Run__c</referenceTo>
        <relationshipLabel>Wig Performers &amp; Runs</relationshipLabel>
        <relationshipName>Wig_Performers_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wig__c</fullName>
        <label>Wig</label>
        <referenceTo>Wig__c</referenceTo>
        <relationshipLabel>Wig Performers &amp; Runs</relationshipLabel>
        <relationshipName>Wig_Performers_Runs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wig Performer &amp; Run</label>
    <nameField>
        <displayFormat>WPR-{000000}</displayFormat>
        <label>Wig Performer &amp; Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wig Performers &amp; Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Test_Wig.cls
@IsTest
private class Test_Wig {
    
    @isTest private static void createWigPerformers(){
        Performer__c performer1 = new Performer__c();
        performer1.Name = 'name';
        Database.insert(performer1);
        
        Performer__c performer2 = new Performer__c();
        performer2.Name = 'name2';
        Database.insert(performer2);

        Wig__c wig = new Wig__c();
        wig.Wig_Label_Ref_Number__c = '1';
        wig.Active_Performer__c = performer1.Id;
        wig.Original_Performer__c = performer2.Id;
        Database.insert(wig);

        System.assertEquals(2, [SELECT ID From Performer_Wig__c].size());

    }

    @isTest private static void createWigPerformerRun() {
        Wig__c wig = new Wig__c();
        wig.Wig_Label_Ref_Number__c = '1';
        Database.insert(wig);
        
        Performer__c performer1 = new Performer__c();
        performer1.Name = 'name';
        Database.insert(performer1);

        Production__c production = new Production__c();
        production.Name = 'production';
        Database.insert(production);

        Run__c run = new Run__c();
        run.Name = 'run';
        run.Production__c = production.Id;
        Database.insert(run);

        Wig_Performer_Run__c wigPerfomerRun = new Wig_Performer_Run__c();
        wigPerfomerRun.Run__c = run.Id;
        wigPerfomerRun.Performer__c = performer1.Id;
        wigPerfomerRun.Wig__c = wig.Id;
        Database.insert(wigPerfomerRun);

        System.assertEquals(1, [SELECT ID From Performer_Wig__c].size());
        System.assertEquals(1, [SELECT ID From Run_Wig__c].size());


        Wig_Performer_Run__c wigPerfomerRun2 = new Wig_Performer_Run__c();
        wigPerfomerRun2.Run__c = run.Id;
        wigPerfomerRun2.Performer__c = performer1.Id;
        wigPerfomerRun2.Wig__c = wig.Id;
        Database.insert(wigPerfomerRun2);

        System.assertEquals(1, [SELECT ID From Performer_Wig__c].size());
        System.assertEquals(1, [SELECT ID From Run_Wig__c].size());

    }
}