retrieve_ENO_DEV1/objects/Performer__c.object
<CustomObject>
    <description>Shows the Performer Profile</description>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Performer_Wig__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Performer Wigs</relationshipLabel>
        <relationshipName>Performer_Wigs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wig__c</fullName>
        <label>Wig</label>
        <referenceTo>Wig__c</referenceTo>
        <relationshipLabel>Performers</relationshipLabel>
        <relationshipName>Performer_Wigs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performer Wig</label>
    <nameField>
        <displayFormat>PW-{00000000}</displayFormat>
        <label>Performer Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performer Wigs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Run__c.object
<CustomObject>
    <description>Holds data of a Production/Show in a season.</description>
    <label>Run</label>
    <nameField>
        <label>Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Run_Wig__c.object
<CustomObject>
    <fields>
        <fullName>Run__c</fullName>
        <label>Run</label>
        <referenceTo>Run__c</referenceTo>
        <relationshipLabel>Wigs</relationshipLabel>
        <relationshipName>Run_Wigs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wig__c</fullName>
        <label>Wig</label>
        <referenceTo>Wig__c</referenceTo>
        <relationshipLabel>Runs</relationshipLabel>
        <relationshipName>Run_Wigs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Run Wig</label>
    <nameField>
        <displayFormat>RW-{00000000}</displayFormat>
        <label>Run Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Run Wigs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Wig__c.object
<CustomObject>
    <label>Wig</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Wig_Performer_Run__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Wig Performers &amp; Runs</relationshipLabel>
        <relationshipName>Wig_Performers_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Run</label>
        <referenceTo>Run__c</referenceTo>
        <relationshipLabel>Wig Performers &amp; Runs</relationshipLabel>
        <relationshipName>Wig_Performers_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wig__c</fullName>
        <label>Wig</label>
        <referenceTo>Wig__c</referenceTo>
        <relationshipLabel>Wig Performers &amp; Runs</relationshipLabel>
        <relationshipName>Wig_Performers_Runs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wig Performer &amp; Run</label>
    <nameField>
        <displayFormat>WPR-{000000}</displayFormat>
        <label>Wig Performer &amp; Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wig Performers &amp; Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Trigger_Wig_Perfomer_Run.cls
public class Trigger_Wig_Perfomer_Run {
    public static void run() {
		if (!Trigger.isExecuting) {
			return;
		}

        Trigger_Wig_Perfomer_Run.setPerformersAndRuns();
    }


    public static void setPerformersAndRuns(){
        if(!(Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate))){
            return;
        }

        Set<Id> wigIds = new Set<Id>();
        List<Wig_Performer_Run__c> iterList = Trigger.new;
        for(Wig_Performer_Run__c wigPerformerRun : iterList){
            wigIds.add(wigPerformerRun.Wig__c);
        }

        Set<Id> performerIds = new Set<Id>();
        Set<Id> runIds = new Set<Id>();
        List<Wig__c> wigs = [
            SELECT Id, 
            (SELECT Id, Performer__c from Performer_Wigs__r),
            (SELECT Id, Run__c from Run_Wigs__r)
            FROM Wig__c
            WHERE Id IN :wigIds
        ];
        for(Wig__c wig : wigs){

            for(Performer_Wig__c performerWig : wig.Performer_Wigs__r){
                performerIds.add(performerWig.Performer__c);
            }

            for(Run_Wig__c runWig : wig.Run_Wigs__r){
                runIds.add(runWig.Run__c);    
            }
        }   

        List<Performer_Wig__c> performerWigsToInsert = new List<Performer_Wig__c>();
        List<Run_Wig__c> runWigsToInsert = new List<Run_Wig__c>();
        for(Wig_Performer_Run__c wigPerformerRun : iterList){
            if(!performerIds.contains(wigPerformerRun.Performer__c)){
                Performer_Wig__c performerWig = new Performer_Wig__c();
                performerWig.Performer__c = wigPerformerRun.Performer__c;
                performerWig.Wig__c = wigPerformerRun.Wig__c;
                performerWigsToInsert.add(performerWig);
            }
            if(!runIds.contains(wigPerformerRun.Run__c)){
                Run_Wig__c runWig = new Run_Wig__c();
                runWig.Run__c = wigPerformerRun.Run__c;
                runWig.Wig__c = wigPerformerRun.Wig__c;
                runWigsToInsert.add(runWig);
            }
        }

        Database.insert(performerWigsToInsert);
        Database.insert(runWigsToInsert);
    }
}