retrieve_ENO_DEV1/objects/Performer__c.object
<CustomObject>
    <description>Shows the Performer Profile</description>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Performer_Wig__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Performer Wigs</relationshipLabel>
        <relationshipName>Performer_Wigs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wig__c</fullName>
        <label>Wig</label>
        <referenceTo>Wig__c</referenceTo>
        <relationshipLabel>Performers</relationshipLabel>
        <relationshipName>Performer_Wigs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Performer Wig</label>
    <nameField>
        <displayFormat>PW-{00000000}</displayFormat>
        <label>Performer Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performer Wigs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Wig__c.object
<CustomObject>
    <fields>
        <fullName>Active_Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Wigs (Active Performer)</relationshipLabel>
        <relationshipName>Wigs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Performer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Wigs</relationshipLabel>
        <relationshipName>Wigs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wig</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Wig Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Trigger_Wig.cls
public class Trigger_Wig {
    public static void run() {
		if (!Trigger.isExecuting) {
			return;
		}

        Trigger_Wig.setPerformers();
    }

    public static void setPerformers(){
        if(!(Trigger.isAfter && (Trigger.isInsert || Trigger.isUpdate))){
            return;
        }

        Set<Id> wigIds = new Set<Id>();
        List<Wig__c> iterList = Trigger.new;
        for(Wig__c wig : iterList){
            wigIds.add(wig.Id);
        }


        Set<Id> performerWigsIds = new Set<Id>();
        List<Performer_Wig__c> performerWigs = [SELECT Wig__c, Performer__c FROM Performer_Wig__c WHERE Wig__c = :wigIds];
        for(Performer_Wig__c pWig : performerWigs){
            performerWigsIds.add(pWig.Performer__c);
        }

        List<Performer_Wig__c> toInsert = new List<Performer_Wig__c>();
        for(Wig__c wig : iterList){
            if(wig.Active_Performer__c != null && 
               !performerWigsIds.contains(wig.Active_Performer__c)
            ){
                Performer_Wig__c newPerformerWig = new Performer_Wig__c();
                newPerformerWig.Wig__c = wig.Id;
                newPerformerWig.Performer__c = wig.Active_Performer__c;
                toInsert.add(newPerformerWig);
            }
            if(wig.Original_Performer__c != wig.Active_Performer__c &&
               wig.Original_Performer__c != null && 
               !performerWigsIds.contains(wig.Original_Performer__c)
            ){
                Performer_Wig__c newPerformerWig = new Performer_Wig__c();
                newPerformerWig.Wig__c = wig.Id;
                newPerformerWig.Performer__c = wig.Original_Performer__c;
                toInsert.add(newPerformerWig);
            }
        }

        Database.insert(toInsert);

    }
}