retrieve_ENO_DEV1/objects/Performer__c.object
<CustomObject>
    <description>Shows the Performer Profile</description>
    <label>Performer</label>
    <nameField>
        <label>Performer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Person_Group__c.object
<CustomObject>
    <label>Person Group</label>
    <nameField>
        <label>Person Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/objects/Person_Group_Performer__c.object
<CustomObject>
    <fields>
        <fullName>Performer__c</fullName>
        <label>Performer</label>
        <referenceTo>Performer__c</referenceTo>
        <relationshipLabel>Person Group Performers</relationshipLabel>
        <relationshipName>Person_Group_Performers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Group__c</fullName>
        <label>Person Group</label>
        <referenceTo>Person_Group__c</referenceTo>
        <relationshipLabel>Person Group Performers</relationshipLabel>
        <relationshipName>Person_Group_Performers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person Group Performer</label>
    <nameField>
        <displayFormat>PGP-{0000000000}</displayFormat>
        <label>Person Group Performer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Group Performers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/Ctrl_PersonGroup.cls
public with sharing class Ctrl_PersonGroup {
    //Get more details when we receive just the id to show on screen.
    @AuraEnabled
    public static List<Id> getPerformers(String personGroupId){
        try {

            List<Person_Group_Performer__c> personGroupPerformers = [
                SELECT Id, Performer__c
                FROM Person_Group_Performer__c
                WHERE Person_Group__c = :personGroupId
            ];

            List<Id> personGroupPerformerIds = new List<Id>();
            for(Person_Group_Performer__c personGroupPerformer : personGroupPerformers){
                personGroupPerformerIds.add(personGroupPerformer.Performer__c);
            }

            return personGroupPerformerIds;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


}