retrieve_ENO_DEV1/objects/System_Log__c.object
<CustomObject>
    <fields>
        <fullName>RecordId__c</fullName>
        <externalId>true</externalId>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/SystemLogUtilsTest.cls
/**
 * Created by sgrigorescu on 5/17/2021.
 */

@IsTest
public with sharing class SystemLogUtilsTest {
    @IsTest
    public static void createSystemLogTest() {
        Test.startTest();
        SystemLogUtils.createSystemLog(null, 'SystemLogUtilsTest.createSystemLogTest', 'ERROR', 'test', 'test details', 'APEX');
        System_Log__c systemLog = [SELECT RecordId__c FROM System_Log__c LIMIT 1];
        System.assertEquals(systemLog.RecordId__c, null, 'RecordId field has incorrect value');
        Test.stopTest();
    }
}