retrieve_ENO_DEV1/objects/System_Log__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>INTERFACE</fullName>
                </value>
                <value>
                    <fullName>PROCESS_BUILDER</fullName>
                </value>
                <value>
                    <fullName>SCHEDULER</fullName>
                </value>
                <value>
                    <fullName>APEX</fullName>
                </value>
                <value>
                    <fullName>EMAIL_SERVICE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>TRACE</fullName>
                </value>
                <value>
                    <fullName>FATAL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <label>Notification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <externalId>true</externalId>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Modstamp__c</fullName>
        <label>System Modstamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve_ENO_DEV1/classes/SystemLogUtils.cls
/**
 * Created by sgrigorescu on 5/11/2021.
 */

global with sharing class SystemLogUtils {

    /**
     * method that inserts System_Log__c object based on parameters
     *
     * @param recordId the id of the record on which the event occurred
     * @param source the method in which the event occurred
     * @param level type of the event
     * @param notification short event description (e.g. exception message)
     * @param details event details (e.g. stack trace)
     * @param category the context where the error occurred
     */
    public static void createSystemLog(String recordId, String source, String level, String notification, String details, String category) {
        System_Log__c log = new System_Log__c(
                RecordId__c = recordId,
                Source__c = source,
                Level__c = level,
                Notification__c = notification,
                Details__c = details,
                System_Modstamp__c = System.now(),
                Category__c = category
        );
        insert log;
    }
}